#!/bin/sh
# Anti-Decorations! ~ For berry(wm)
# By ThatGeekyWeeb
# https://github.com/ThatGeekyWeeb/Squid-Dots
while getopts ":w:" opt
do
  case "$opt" in
    w ) windowNAME=$OPTARG;;
  esac
done
windowNAME="Discord"
func_1(){
var1=$(wmctrl -l | grep "  "$(wmctrl -d | grep "\*" | cut -f1 -d" ") | grep "$windowNAME" | cut -f1 -d" ")
until xprop -id "$var1" BERRY_WINDOW_STATUS | grep 'true' -q; do
	sleep 1
done
wmctrl -a "$var1" -i | berryc toggle_decorations
}
while sleep 1
do
while wmctrl -l | grep "  "$(wmctrl -d | grep "\*" | cut -f1 -d" ") | grep "$windowNAME " -q; do
	printf "Subprocess found waiting\n"
	sleep 1
done
printf '%b Found!\n' "$windowNAME"
until wmctrl -l | grep "  "$(wmctrl -d | grep "\*" | cut -f1 -d" ") | grep "$windowNAME" -q; do
	printf '%b not found!\n' "$windowNAME"
 	sleep 1
done
func_1
done
