#!/bin/sh
# Auto-ReRES ~ For berry(wm)
# By ThatGeekyWeeb & Periish
# https://github.com/ThatGeekyWeeb/Squid-Dots
while getopts ":w:" opt
do
  case "$opt" in
    w ) windowNAME=$OPTARG;;
  esac
done
get_ws () {
while read -r ws status _; do
    case $status in
        '*') printf '%s\n' "$ws"
    esac
done <<EOF
$(wmctrl -d)
EOF
}
windowNAME="Minecraft Launcher"
windowNAME_sub="Minecraft 1.8.9"
while sleep 1
do
until wmctrl -l | grep "  "$(wmctrl -d | grep "\*" | cut -f1 -d" ") | grep "$windowNAME" -q; do
	printf '%b not found\n' "$windowNAME"
	sleep 1
done
xrandr --output HDMI1 --mode 1920x1080
until wmctrl -l | grep "  "$(get_ws) | grep "$windowNAME_sub" -q; do
	printf 'Subprocess not yet found\n'
	sleep 1
done
xrandr --output HDMI1 --mode 1920x1080R
printf 'Done!\n'
printf 'Waiting for Subprocess to finish\n'
while wmctrl -l | grep "  "$(get_ws) | grep "$windowNAME_sub" -q; do
	printf 'Waiting for Subprocess to finish\n'
	sleep 1
done
printf 'Subprocess has finished\n'
printf 'Reseting res\n'
sleep 5
xrandr --output HDMI1 --mode 1920x1080R
printf 'Done!\n'
done
