#!/bin/sh
# Anti-Decorations! ~ For berry(wm)
# By ThatGeekyWeeb
# https://github.com/ThatGeekyWeeb/Squid-Dots
while getopts ":w:" opt
do
  case "$opt" in
    w ) windowNAME=$OPTARG;;
  esac
done
windowNAME="Discord"

get_ws () {
while read -r ws status _; do
    case $status in
        '*') printf '%s\n' "$ws"
    esac
done <<EOF
$(wmctrl -d)
EOF
}

while sleep 1
do
while wmctrl -l | grep "  "$(get_ws) | grep "$windowNAME""[[:space:]][A-z]" -q; do
	printf "Subprocess found waiting\n"
	sleep 5
done
while wmctrl -l | grep "  "$(get_ws) | grep "$windowNAME""[[:space:]][A-z]" -q; do
	printf "Subprocess found waiting\n"
	sleep 5
done
printf '%b Found!\n' "$windowNAME"
until wmctrl -l | grep "  "$(get_ws) | grep "$windowNAME" -q; do
	printf '%b not found!\n' "$windowNAME"
 	sleep 2
done
while wmctrl -l | grep "  "$(get_ws) | grep "$windowNAME""[[:space:]][A-z]" -q; do
	printf "Subprocess found waiting\n"
	sleep 5
done
winID=$(wmctrl -l | grep "  "$(get_ws) | grep "$windowNAME" | cut -f1 -d" ")
until xprop -id $winID BERRY_WINDOW_STATUS | grep 'true' -q; do
	sleep 1
done
printf 'Remove titlebar\n'
sleep 5 && wmctrl -a "$winID" -i
sleep 1 && berryc toggle_decorations
done
